[package]
name = "nx-aarch64-build"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies.cu]
package = "pistonite-cu"
version = "0.9.4"
features = [ "cli", "coroutine-heavy", "derive", "fs", "json" ]

[dependencies]
hex = "0.4.3"
liblzma = { version = "0.4.8", features = ["parallel", "static"] }
sha2 = "0.11.0"
tar = "0.4.46"
tokio = "1"
ureq = "3.4.2"
